from abc import ABC, abstractmethod
from typing import Any


class CollaborationRepository(ABC):
    @abstractmethod
    def get_group(self, group_id) -> Any: ...

    @abstractmethod
    def is_group_member(self, group_id, user_id) -> bool: ...

    @abstractmethod
    def can_manage_group_planning(self, group_id, user_id) -> bool: ...

    @abstractmethod
    def list_polls(self, group_id) -> Any: ...

    @abstractmethod
    def get_poll_for_option(self, option_id) -> Any: ...

    @abstractmethod
    def create_poll(self, group_id, user_id, title, closes_at, options) -> Any: ...

    @abstractmethod
    def cast_vote(self, poll_id, option_id, user_id, vote_status) -> Any: ...

    @abstractmethod
    def get_plan(self, plan_id) -> Any: ...

    @abstractmethod
    def can_access_plan(self, plan_id, user_id) -> bool: ...

    @abstractmethod
    def can_manage_plan(self, plan_id, user_id) -> bool: ...

    @abstractmethod
    def is_plan_member(self, plan_id, user_id) -> bool: ...

    @abstractmethod
    def activity_belongs_to_plan(self, activity_id, plan_id) -> bool: ...

    @abstractmethod
    def get_plan_for_export(self, plan_id) -> Any: ...

    @abstractmethod
    def now(self) -> Any: ...

    @abstractmethod
    def list_work_items(self, plan_id) -> Any: ...

    @abstractmethod
    def get_work_item(self, item_id) -> Any: ...

    @abstractmethod
    def create_work_item(self, plan_id, user_id, data) -> Any: ...

    @abstractmethod
    def update_work_item(self, item_id, data) -> Any: ...

    @abstractmethod
    def delete_work_item(self, item_id) -> None: ...

    @abstractmethod
    def list_comments(self, plan_id, activity_id=None) -> Any: ...

    @abstractmethod
    def get_comment(self, comment_id) -> Any: ...

    @abstractmethod
    def create_comment(self, plan_id, user_id, data) -> Any: ...

    @abstractmethod
    def update_comment(self, comment_id, body) -> Any: ...

    @abstractmethod
    def delete_comment(self, comment_id) -> None: ...

    @abstractmethod
    def set_reaction(self, comment_id, user_id, reaction) -> Any: ...

    @abstractmethod
    def toggle_pin(self, comment_id, user_id) -> Any: ...

    @abstractmethod
    def clone_plan(self, source_plan_id, user_id, data) -> Any: ...
