from abc import ABC, abstractmethod


class ExperienceRepository(ABC):
    @abstractmethod
    def is_group_member(self, group_id, user_id): ...

    @abstractmethod
    def can_manage_group(self, group_id, user_id): ...

    @abstractmethod
    def list_group_polls(self, group_id, user_id): ...

    @abstractmethod
    def create_group_poll(self, group_id, user_id, data): ...

    @abstractmethod
    def get_group_poll(self, poll_id, for_update=False): ...

    @abstractmethod
    def replace_poll_votes(self, poll, user_id, option_ids): ...

    @abstractmethod
    def close_poll(self, poll_id): ...

    @abstractmethod
    def can_access_conversation(self, conversation_id, user_id): ...

    @abstractmethod
    def list_live_locations(self, conversation_id): ...

    @abstractmethod
    def create_live_location(self, conversation_id, user_id, data): ...

    @abstractmethod
    def get_live_location(self, share_id, for_update=False): ...

    @abstractmethod
    def update_live_location(self, share_id, data): ...

    @abstractmethod
    def expire_live_locations(self, now): ...

    @abstractmethod
    def global_search(self, user_id, query, types, limit): ...
