"""
Django settings for planpalapp project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import cloudinary
from urllib.parse import quote_plus
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file with explicit path
# .env is in the same directory as manage.py (BASE_DIR)
load_dotenv()





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    '10.0.2.2,localhost,127.0.0.1,192.168.1.41,planpal-backend.fly.dev'
).split(',')

CSRF_TRUSTED_ORIGINS = [
    "https://planpal-backend.fly.dev",
    "http://planpal-backend.fly.dev",
]

# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server for Channels - must be first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'oauth2_provider',
    'ckeditor',
    'ckeditor_uploader',
    'channels',  # Django Channels for WebSocket
    
    'planpals',
]

MIDDLEWARE = [
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'planpals.shared.paginators.StandardResultsPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'planpals.shared.exception_handler.custom_exception_handler',
    # Datetime format settings to ensure timezone-aware serialization
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',  # ISO 8601 with timezone
    'DATETIME_INPUT_FORMATS': [
        'iso-8601',  # Support ISO 8601 format with timezone
        '%Y-%m-%dT%H:%M:%S%z',
        '%Y-%m-%dT%H:%M:%S.%f%z',
        '%Y-%m-%dT%H:%M:%S',
        '%Y-%m-%dT%H:%M:%S.%f',
    ],
}

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    
    
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,        # 1 hour
    'REFRESH_TOKEN_EXPIRE_SECONDS': 3600 * 24 * 7,  # 1 week
    'ROTATE_REFRESH_TOKEN': True,               # Rotate refresh tokens for security
}

ROOT_URLCONF = 'planpalapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'planpalapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support DATABASE_URL for production (Aiven MySQL) and .env for local
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Fix SSL parameter for mysqlclient - convert ssl-mode to ssl dict
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    # Remove invalid ssl-mode parameter and add proper SSL config
    DATABASES['default']['OPTIONS'].pop('ssl-mode', None)
    DATABASES['default']['OPTIONS']['ssl'] = {'ssl_mode': 'REQUIRED'}
else:
    # Fallback for local development without DATABASE_URL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }

# else:
#     # Local development
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': os.getenv('DB_NAME'),
#             'USER': os.getenv('DB_USER'),
#             'PASSWORD': os.getenv('DB_PASSWORD'),
#             'HOST': os.getenv('DB_HOST', 'localhost'),
#             'PORT': os.getenv('DB_PORT', '3306'),
#         }
#     }

AUTH_USER_MODEL = 'planpals.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Timezone configuration - Asia/Ho_Chi_Minh (UTC+7)
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic in production

# WhiteNoise configuration for serving static files efficiently
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# CORS settings — restrict in production, allow all in development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://planpal-backend.fly.dev",
    ]
CORS_ALLOW_CREDENTIALS = True


# # Media files settings
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Configure Cloudinary for image uploads
_cloud_name = CLOUDINARY_STORAGE.get('CLOUD_NAME')
_api_key = CLOUDINARY_STORAGE.get('API_KEY')
_api_secret = CLOUDINARY_STORAGE.get('API_SECRET')
if _cloud_name and _api_key and _api_secret:
    cloudinary.config(
        cloud_name=_cloud_name,
        api_key=_api_key,
        api_secret=_api_secret
    )

# Use Cloudinary for default file storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ============================================================================
# EXTERNAL API CONFIGURATIONS
# ============================================================================

# Goong Map API - PRIMARY LOCATION SERVICE FOR VIETNAM
GOONG_API_KEY = os.getenv('GOONG_API_KEY')

# OpenStreetMap/Nominatim - BACKUP OPTION (DISABLED)
# NOMINATIM_BASE_URL = os.getenv('NOMINATIM_BASE_URL', 'https://nominatim.openstreetmap.org')
# NOMINATIM_USER_AGENT = os.getenv('NOMINATIM_USER_AGENT', 'PlanPal-Student-Project/1.0')
# OVERPASS_API_URL = os.getenv('OVERPASS_API_URL', 'https://overpass-api.de/api/interpreter')

# Firebase Cloud Messaging Configuration
FIREBASE_SERVICE_ACCOUNT_PATH = os.getenv('FIREBASE_SERVICE_ACCOUNT_PATH', './firebase_service_account.json')
FCM_PROJECT_ID = os.getenv('FCM_PROJECT_ID', 'alapp-ffa74')

# Email configuration for notifications
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Ensure logs directory exists so FileHandler won't fail at import time
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'planpal.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG',
    },
    'loggers': {
        'planpals.services': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ============================================================================
# DRF-SPECTACULAR SETTINGS (Swagger/OpenAPI Documentation)
# ============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'PlanPal API',
    'DESCRIPTION': 'API documentation for PlanPal - Social Travel Planning Application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'expandResponses': 'all',
    },
    'SCHEMA_PATH_PREFIX': '/api/',
    'SECURITY': [
        {
            'type': 'oauth2',
            'flows': {
                'authorizationCode': {
                    'authorizationUrl': '/o/authorize/',
                    'tokenUrl': '/o/token/',
                    'scopes': {
                        'read': 'Read access to API',
                        'write': 'Write access to API'
                    }
                }
            }
        }
    ],
}

# ============================================================================
# CKEDITOR SETTINGS
# ============================================================================

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

CLIENT_ID = os.getenv('CLIENT_ID')
# CLIENT_SECRET = os.getenv('CLIENT_SECRET')

# ============================================================================
# CELERY SETTINGS
# ============================================================================
# Redis local trong container khi deploy, localhost khi dev
CELERY_REDIS_URL = os.getenv('CELERY_REDIS_URL')
CACHE_REDIS_URL = os.getenv('CACHE_REDIS_URL')
CHANNEL_REDIS_URL = os.getenv('CHANNEL_REDIS_URL') or CELERY_REDIS_URL
USE_REDIS_CACHE = _env_flag('USE_REDIS_CACHE', default=bool(CACHE_REDIS_URL))
USE_REDIS_CHANNELS = _env_flag('USE_REDIS_CHANNELS', default=bool(CHANNEL_REDIS_URL))

# ============================================================================
# DJANGO CACHE (Redis via django-redis)
# ============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',   # DB 1 — separate from Celery/Channels (DB 0)
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'planpal',
        'TIMEOUT': 300,   # Default 5 min TTL
    }
}

if USE_REDIS_CACHE and CACHE_REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': CACHE_REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'planpal',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'planpal-local-cache',
            'TIMEOUT': 300,
        }
    }

# TIME_ZONE and USE_TZ are already configured above in Internationalization section

CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL') or CELERY_REDIS_URL or 'memory://'
CELERY_RESULT_BACKEND = (
    os.getenv('CELERY_RESULT_BACKEND')
    or CELERY_REDIS_URL
    or 'cache+memory://'
)

# ---------------------------------------------------------------------------
# Queue Architecture — 4 priority queues
# ---------------------------------------------------------------------------
# Start workers with:
#   celery -A planpalapp worker -Q high_priority,default,plan_status,low_priority \
#          --concurrency=4 -l info
# Or dedicated per-queue workers for isolation:
#   celery -A planpalapp worker -Q high_priority -c 4 -n high@%h
#   celery -A planpalapp worker -Q default,plan_status -c 2 -n default@%h
#   celery -A planpalapp worker -Q low_priority -c 1 -n low@%h

from kombu import Queue

CELERY_TASK_QUEUES = [
    Queue('high_priority', routing_key='high'),     # Push notifs, chat fan-out
    Queue('default', routing_key='default'),         # General event processing
    Queue('plan_status', routing_key='plan_status'), # Scheduled plan lifecycle (ETA)
    Queue('low_priority', routing_key='low'),        # Analytics, cleanup
]
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# ---------------------------------------------------------------------------
# Task routing — map every task to the correct queue
# ---------------------------------------------------------------------------
CELERY_TASK_ROUTES = {
    # Plan lifecycle (ETA-scheduled) → plan_status
    'planpals.tasks.start_plan_task': {'queue': 'plan_status'},
    'planpals.tasks.complete_plan_task': {'queue': 'plan_status'},
    # Push notifications → high_priority
    'planpals.shared.tasks.send_push_notification_task': {'queue': 'high_priority'},
    'planpals.shared.tasks.send_event_push_notification_task': {'queue': 'high_priority'},
    # Chat fan-out → high_priority
    'planpals.chat.infrastructure.tasks.fanout_chat_push_notification_task': {'queue': 'high_priority'},
    # Analytics / periodic → low_priority
    'planpals.shared.analytics_tasks.aggregate_daily_statistics_task': {'queue': 'low_priority'},
    'planpals.shared.analytics_tasks.cleanup_expired_offline_events_task': {'queue': 'low_priority'},
    'planpals.shared.analytics_tasks.cleanup_invalid_fcm_tokens_task': {'queue': 'low_priority'},
}

# ---------------------------------------------------------------------------
# Time limits — prevent runaway tasks
# ---------------------------------------------------------------------------
CELERY_TASK_SOFT_TIME_LIMIT = 120      # Soft limit: 2 min (raises SoftTimeLimitExceeded)
CELERY_TASK_TIME_LIMIT = 300           # Hard kill: 5 min
CELERY_TASK_ACKS_LATE = True           # ACK after execution → re-deliver on worker crash
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Fair scheduling across queues

# ---------------------------------------------------------------------------
# Reliability
# ---------------------------------------------------------------------------
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Re-queue if worker killed mid-task
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200   # Recycle workers to prevent memory leaks
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,   # 1 h — must exceed longest ETA
    'max_retries': 3,
    'interval_start': 0,
    'interval_step': 0.2,
    'interval_max': 0.5,
}

# ---------------------------------------------------------------------------
# Rate limiting defaults (overridable per-task)
# ---------------------------------------------------------------------------
CELERY_TASK_DEFAULT_RATE_LIMIT = '100/m'   # 100 tasks/min default

# ---------------------------------------------------------------------------
# Celery Beat — periodic task schedule
# ---------------------------------------------------------------------------
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'aggregate-daily-statistics': {
        'task': 'planpals.shared.analytics_tasks.aggregate_daily_statistics_task',
        'schedule': crontab(hour=2, minute=0),   # Every day at 02:00 AM
    },
    'cleanup-expired-offline-events': {
        'task': 'planpals.shared.analytics_tasks.cleanup_expired_offline_events_task',
        'schedule': crontab(hour=3, minute=0),   # Every day at 03:00 AM
    },
    'cleanup-invalid-fcm-tokens': {
        'task': 'planpals.shared.analytics_tasks.cleanup_invalid_fcm_tokens_task',
        'schedule': crontab(hour=4, minute=0, day_of_week=0),  # Weekly Sunday 04:00
    },
}

# ============================================================================
# DJANGO CHANNELS SETTINGS (WebSocket Support)
# ============================================================================
ASGI_APPLICATION = 'planpalapp.asgi.application'

CHANNEL_LAYERS = {
    'default': (
        {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [CHANNEL_REDIS_URL],
                'capacity': 1500,
                'expiry': 60,
                'symmetric_encryption_keys': [SECRET_KEY],
            },
        }
        if USE_REDIS_CHANNELS and CHANNEL_REDIS_URL
        else {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    ),
}
