# Generated by Django 5.2.4 on 2025-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planactivity',
            name='google_place_id',
        ),
        migrations.AddField(
            model_name='planactivity',
            name='goong_place_id',
            field=models.CharField(blank=True, help_text='Goong Map API place ID', max_length=200),
        ),
    ]
