# Generated by Django 5.2.6 on 2026-03-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='planpal_cha_updated_18a695_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='planpal_con_updated_767082_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='planpal_fri_updated_de74b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendshiprejection',
            name='planpal_fri_updated_559f5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='planpal_gro_updated_a90080_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='planpal_gro_updated_937700_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereadstatus',
            name='planpal_mes_updated_b152ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereadstatus',
            name='planpal_mes_message_3f86c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='planpal_pla_updated_1fc8db_idx',
        ),
        migrations.RemoveIndex(
            model_name='planactivity',
            name='planpal_pla_updated_be8f88_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='planpal_use_updated_cdbae8_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'user_a'], name='planpal_con_convers_c66fee_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'user_b'], name='planpal_con_convers_827a84_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'start_date'], name='planpal_pla_status_e9a0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'end_date'], name='planpal_pla_status_be5d46_idx'),
        ),
    ]
