# Generated by Django 5.2.4 on 2025-09-08 12:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='planpal_con_created_119e9f_idx',
            old_name='planpals_co_created_2b3948_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='planpal_con_updated_767082_idx',
            old_name='planpals_co_updated_89666a_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Avatar cuộc trò chuyện', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Cuộc trò chuyện có đang hoạt động không'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Thời gian tin nhắn cuối cùng (denormalized)', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, help_text='Tên cuộc trò chuyện (auto-generate nếu để trống)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='planpal_con_convers_405e96_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='planpal_con_last_me_07cda2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', 'last_message_at'], name='planpal_con_is_acti_5f5fb7_idx'),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='planpal_conversations',
        ),
    ]
