# Generated by Django 5.2.4 on 2025-08-17 08:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0002_rename_google_place_id_to_goong_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='budget',
        ),
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Ảnh đại diện nhóm', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(help_text='Nhóm', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='planpals.group'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Sắp bắt đầu'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='draft', help_text='Trạng thái kế hoạch', max_length=20),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='activity_type',
            field=models.CharField(choices=[('eating', 'Ăn uống'), ('resting', 'Nghỉ ngơi'), ('moving', 'Di chuyển'), ('sightseeing', 'Tham quan'), ('shopping', 'Mua sắm'), ('entertainment', 'Giải trí'), ('event', 'Sự kiện'), ('sport', 'Thể thao'), ('study', 'Học tập'), ('work', 'Công việc'), ('other', 'Khác')], db_index=True, default='other', help_text='Loại hoạt động', max_length=20),
        ),
    ]
