# Generated by Django 5.2.4 on 2025-09-13 13:06

import cloudinary.models
import django.db.models.deletion
import planpals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', planpals.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='planpal_cha_group_i_ead640_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='planpal_cha_group_i_3bc904_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='friendshiprejection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='planactivity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Attachment file (image, document, etc.)', max_length=255, null=True, verbose_name='auto'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size (bytes)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='The conversation contains this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planpals.conversation'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Message has been deleted (soft delete)'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Message has been edited'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='location_name',
            field=models.CharField(blank=True, help_text='Location name', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'File đính kèm'), ('location', 'Vị trí'), ('system', 'Thông báo hệ thống')], db_index=True, default='text', help_text='Message type', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Reply to message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='planpals.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Sender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Conversation avatar', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Chat cá nhân'), ('group', 'Chat nhóm')], db_index=True, help_text='Loại cuộc trò chuyện', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='group',
            field=models.OneToOneField(blank=True, help_text='Group (only for group conversations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='planpals.group'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last message in the conversation', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, help_text='Coversation name', max_length=200),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(help_text='Participants in the conversation', related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(help_text='Message that has been read', on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='planpals.chatmessage'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the message was read'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(help_text='User who has read the message', on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='activity_type',
            field=models.CharField(choices=[('eating', 'Ăn uống'), ('resting', 'Nghỉ ngơi'), ('moving', 'Di chuyển'), ('sightseeing', 'Tham quan'), ('shopping', 'Mua sắm'), ('entertainment', 'Giải trí'), ('event', 'Sự kiện'), ('sport', 'Thể thao'), ('study', 'Học tập'), ('work', 'Công việc'), ('other', 'Khác')], db_index=True, default='other', help_text='Activity type', max_length=20),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Activity description'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the activity'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost (VND)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Has the activity been completed?'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='location_address',
            field=models.TextField(blank=True, help_text='Detailed address'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='location_name',
            field=models.CharField(blank=True, help_text='Name of the location', max_length=200),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of activity in the day'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='plan',
            field=models.ForeignKey(help_text='Plan of this activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planpals.plan'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the activity'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='title',
            field=models.CharField(help_text='Activity name', max_length=200),
        ),
    ]
