# Generated by Django 5.2.4 on 2025-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0003_remove_plan_budget_group_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Sắp bắt đầu'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='upcoming', help_text='Trạng thái kế hoạch', max_length=20),
        ),
    ]
