# Generated by Django 5.2.4 on 2025-08-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0004_alter_plan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='planactivity',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Hoạt động đã hoàn thành chưa'),
        ),
    ]
