# Generated by Django 5.2.4 on 2025-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0004_fix_image_attachment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Chat cá nhân'), ('group', 'Chat nhóm')], db_index=True, help_text='Conversation type', max_length=10),
        ),
    ]
