# Generated by Django 5.2.6 on 2026-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0004_notification_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('CHANGE_ROLE', 'Change Role'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('monthly_active_users', models.PositiveIntegerField(default=0)),
                ('plans_created', models.PositiveIntegerField(default=0)),
                ('plans_completed', models.PositiveIntegerField(default=0)),
                ('group_joins', models.PositiveIntegerField(default=0)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('notifications_opened', models.PositiveIntegerField(default=0)),
                ('notification_open_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('plan_creation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('plan_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('group_join_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planpal_daily_metrics',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='analytics_metric_date_idx')],
            },
        ),
    ]
