# Generated by Django 5.2.6 on 2026-04-14 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_missing_budgets(apps, schema_editor):
    Plan = apps.get_model('planpals', 'Plan')
    Budget = apps.get_model('planpals', 'Budget')

    existing_plan_ids = set(Budget.objects.values_list('plan_id', flat=True))
    missing = [
        Budget(plan_id=plan_id, total_budget=0, currency='VND')
        for plan_id in Plan.objects.exclude(id__in=existing_plan_ids).values_list('id', flat=True)
    ]
    if missing:
        Budget.objects.bulk_create(missing, batch_size=500)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0005_alter_auditlog_action_dailymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='expense_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='expenses_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('CHANGE_ROLE', 'Change Role'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_REMINDER', 'Plan Reminder'), ('GROUP_JOIN', 'Group Join'), ('GROUP_INVITE', 'Group Invite'), ('ROLE_CHANGED', 'Role Changed'), ('PLAN_UPDATED', 'Plan Updated'), ('NEW_MESSAGE', 'New Message'), ('BUDGET_ALERT', 'Budget Alert'), ('LARGE_EXPENSE', 'Large Expense')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_record', to='planpals.plan')),
            ],
            options={
                'db_table': 'planpal_budgets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan'], name='budget_plan_idx'), models.Index(fields=['created_at'], name='budget_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='planpals.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_expenses',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plan', 'created_at'], name='expense_plan_created_idx'), models.Index(fields=['user'], name='expense_user_idx'), models.Index(fields=['category'], name='expense_category_idx'), models.Index(fields=['plan', 'category'], name='expense_plan_category_idx'), models.Index(fields=['created_at', 'id'], name='expense_cursor_idx')],
            },
        ),
        migrations.RunPython(create_missing_budgets, noop_reverse),
    ]
