# Generated by Django 5.2.4 on 2025-09-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0005_alter_conversation_conversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, help_text='Message content', null=True),
        ),
    ]
