# Generated by Django 5.2.4 on 2025-09-20 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0006_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Attachment file (image, document, etc.)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
