# Generated by Django 5.2.6 on 2026-04-19 13:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0006_dailymetric_expense_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Attachment file (image, document, etc.)', max_length=255, null=True, verbose_name='file'),
        ),
    ]
