# Generated by Django 5.2.6 on 2026-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0007_alter_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_resource_type',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Cloudinary resource type for attachment',
                max_length=20,
            ),
        ),
    ]
