# Generated by Django 5.2.6 on 2026-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0010_audit_activity_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('plan_creator', 'Plan creator'), ('admin', 'Quản trị viên'), ('member', 'Thành viên')], db_index=True, default='member', help_text='Role', max_length=20),
        ),
    ]
