# Generated by Django 5.2.6 on 2026-04-26 10:18

from django.db import migrations, models
from django.utils import timezone


def mark_existing_active_users_verified(apps, schema_editor):
    User = apps.get_model('planpals', 'User')
    User.objects.filter(is_active=True, email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )


def unmark_existing_users_verified(apps, schema_editor):
    User = apps.get_model('planpals', 'User')
    User.objects.update(email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0011_align_groupmembership_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Time when the user confirmed ownership of their email address', null=True),
        ),
        migrations.RunPython(
            mark_existing_active_users_verified,
            reverse_code=unmark_existing_users_verified,
        ),
    ]
