# Generated by Django 5.2.6 on 2026-05-15 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_expense_shares(apps, schema_editor):
    Expense = apps.get_model('planpals', 'Expense')
    ExpenseParticipant = apps.get_model('planpals', 'ExpenseParticipant')

    expenses = list(Expense.objects.filter(paid_by_user__isnull=True))
    for expense in expenses:
        expense.paid_by_user_id = expense.user_id
    if expenses:
        Expense.objects.bulk_update(expenses, ['paid_by_user'])

    existing_expense_ids = set(
        ExpenseParticipant.objects.values_list('expense_id', flat=True)
    )
    participants = [
        ExpenseParticipant(
            expense_id=expense.id,
            user_id=expense.user_id,
            owed_amount=expense.amount,
            settled_amount=0,
            balance=0,
        )
        for expense in Expense.objects.all().only('id', 'user_id', 'amount')
        if expense.id not in existing_expense_ids
    ]
    if participants:
        ExpenseParticipant.objects.bulk_create(participants, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0013_group_audit_action_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planpal_expense_participants',
                'ordering': ['expense_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planpal_settlements',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='VND', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_plan_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_strategy',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact amount')], db_index=True, default='equal', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_REMINDER', 'Plan Reminder'), ('GROUP_JOIN', 'Group Join'), ('GROUP_INVITE', 'Group Invite'), ('ROLE_CHANGED', 'Role Changed'), ('PLAN_UPDATED', 'Plan Updated'), ('NEW_MESSAGE', 'New Message'), ('BUDGET_ALERT', 'Budget Alert'), ('LARGE_EXPENSE', 'Large Expense'), ('EXPENSE_ADDED', 'Expense Added'), ('SETTLEMENT_REQUESTED', 'Settlement Requested')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by_user'], name='expense_paid_by_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['plan', 'split_strategy'], name='expense_plan_split_idx'),
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='planpals.expense'),
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='planpals.plan'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['expense', 'user'], name='expense_participant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['user'], name='expense_part_user_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['expense'], name='expense_part_expense_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='unique_expense_participant'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['plan', 'status'], name='settlement_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['from_user'], name='settlement_from_user_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['to_user'], name='settlement_to_user_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settled_at'], name='settlement_settled_at_idx'),
        ),
        migrations.RunPython(backfill_legacy_expense_shares, noop_reverse),
    ]
