# Generated by Django 5.2.6 on 2026-05-15 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0014_expense_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('GROUP_INVITE_CREATED', 'Group Invite Created'), ('GROUP_INVITE_REVOKED', 'Group Invite Revoked'), ('GROUP_JOINED_VIA_INVITE', 'Group Joined Via Invite'), ('GROUP_INVITE_FAILED', 'Group Invite Failed'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('token', models.CharField(db_index=True, help_text='Cryptographically secure URL-safe invite token', max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Invite expiration time. Null means no explicit expiration.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum accepted joins. Null means unlimited.', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Accepted join count for this invite.')),
                ('created_by', models.ForeignKey(help_text='Admin who generated this invite', on_delete=django.db.models.deletion.CASCADE, related_name='created_group_invites', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this invite allows users to join', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='planpals.group')),
            ],
            options={
                'db_table': 'planpal_group_invites',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='planpal_gro_created_7a3521_idx'), models.Index(fields=['group', 'is_active'], name='group_invite_group_active_idx'), models.Index(fields=['expires_at'], name='group_invite_expires_idx'), models.Index(fields=['created_by'], name='group_invite_creator_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('max_uses__gt', 0), _connector='OR'), name='group_invite_max_uses_positive'), models.CheckConstraint(condition=models.Q(('current_uses__gte', 0)), name='group_invite_current_uses_non_negative')],
            },
        ),
    ]
