# Generated by Django 5.2.6 on 2026-05-15 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0015_alter_auditlog_action_groupinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Review state for this join request', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
            ],
            options={
                'db_table': 'planpal_group_join_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', help_text='Controls whether invite links auto-join or require admin approval', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('GROUP_INVITE_CREATED', 'Group Invite Created'), ('GROUP_INVITE_REVOKED', 'Group Invite Revoked'), ('GROUP_JOINED_VIA_INVITE', 'Group Joined Via Invite'), ('GROUP_INVITE_FAILED', 'Group Invite Failed'), ('GROUP_JOIN_REQUESTED', 'Group Join Requested'), ('GROUP_JOIN_REQUEST_APPROVED', 'Group Join Request Approved'), ('GROUP_JOIN_REQUEST_REJECTED', 'Group Join Request Rejected'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['visibility', 'is_active', 'created_at'], name='planpal_gro_visibil_4fcfa0_idx'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(help_text='Group the user requested to join', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='planpals.group'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='invite',
            field=models.ForeignKey(blank=True, help_text='Invite link that produced the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='planpals.groupinvite'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved or rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(help_text='User requesting access to the group', on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['created_at'], name='planpal_gro_created_4ab284_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status'], name='grp_join_req_group_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', 'status'], name='group_join_req_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['invite', 'status'], name='grp_join_req_inv_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'user')},
        ),
    ]
