# Generated by Django 5.2.6 on 2026-08-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_expense_payments(apps, schema_editor):
    Expense = apps.get_model('planpals', 'Expense')
    ExpensePayment = apps.get_model('planpals', 'ExpensePayment')

    paid_expense_ids = set(ExpensePayment.objects.values_list('expense_id', flat=True))
    payments = [
        ExpensePayment(
            expense_id=expense.id,
            user_id=expense.paid_by_user_id or expense.user_id,
            amount=expense.amount,
        )
        for expense in Expense.objects.all().only(
            'id', 'user_id', 'paid_by_user_id', 'amount'
        )
        if expense.id not in paid_expense_ids
    ]
    if payments:
        ExpensePayment.objects.bulk_create(payments, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0016_groupjoinrequest_group_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='planpals.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_expense_payments',
                'ordering': ['expense_id', 'user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['expense', 'user'], name='expense_payment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['user'], name='expense_payment_user_idx2'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='unique_expense_payment_user'),
        ),
        migrations.RunPython(backfill_expense_payments, migrations.RunPython.noop),
    ]
