# Generated by Django 5.2.6 on 2026-09-10 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0017_expense_payment_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this plan is a reusable template'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('CREATE_AVAILABILITY_POLL', 'Create Availability Poll'), ('CREATE_WORK_ITEM', 'Create Work Item'), ('UPDATE_WORK_ITEM', 'Update Work Item'), ('CREATE_COMMENT', 'Create Comment'), ('PIN_COMMENT', 'Pin Comment'), ('UNPIN_COMMENT', 'Unpin Comment'), ('CLONE_PLAN', 'Clone Plan'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('GROUP_INVITE_CREATED', 'Group Invite Created'), ('GROUP_INVITE_REVOKED', 'Group Invite Revoked'), ('GROUP_JOINED_VIA_INVITE', 'Group Joined Via Invite'), ('GROUP_INVITE_FAILED', 'Group Invite Failed'), ('GROUP_JOIN_REQUESTED', 'Group Join Requested'), ('GROUP_JOIN_REQUEST_APPROVED', 'Group Join Request Approved'), ('GROUP_JOIN_REQUEST_REJECTED', 'Group Join Request Rejected'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.CreateModel(
            name='AvailabilityPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('title', models.CharField(max_length=200)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_availability_polls', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_polls', to='planpals.group')),
            ],
            options={
                'db_table': 'planpal_availability_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='planpals.availabilitypoll')),
            ],
            options={
                'db_table': 'planpal_availability_options',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('status', models.CharField(choices=[('available', 'available'), ('maybe', 'maybe'), ('unavailable', 'unavailable')], max_length=20)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planpals.availabilityoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_availability_votes',
            },
        ),
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('body', models.TextField(max_length=4000)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planpals.planactivity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='planpals.plancomment')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_plan_comments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planpals.plan')),
            ],
            options={
                'db_table': 'planpal_comments',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('reaction', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='planpals.plancomment')),
            ],
            options={
                'db_table': 'planpal_comment_reactions',
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='planpals.plancomment')),
            ],
            options={
                'db_table': 'planpal_comment_mentions',
            },
        ),
        migrations.CreateModel(
            name='PlanWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('task', 'task'), ('checklist', 'checklist')], db_index=True, default='task', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('done', 'done')], db_index=True, default='todo', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='planpals.planactivity')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_work_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plan_work_items', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='planpals.plan')),
            ],
            options={
                'db_table': 'planpal_work_items',
                'ordering': ['status', 'due_at', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='availabilitypoll',
            index=models.Index(fields=['group', 'is_closed', 'created_at'], name='planpal_ava_group_i_392882_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityoption',
            index=models.Index(fields=['poll', 'start_at'], name='planpal_ava_poll_id_711f94_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoption',
            constraint=models.UniqueConstraint(fields=('poll', 'start_at', 'end_at'), name='unique_poll_time_option'),
        ),
        migrations.AddIndex(
            model_name='availabilityvote',
            index=models.Index(fields=['option', 'status'], name='planpal_ava_option__dd0be3_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityvote',
            index=models.Index(fields=['user', 'created_at'], name='planpal_ava_user_id_7e2e9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='unique_availability_vote'),
        ),
        migrations.AddIndex(
            model_name='plancomment',
            index=models.Index(fields=['plan', 'is_pinned', 'created_at'], name='planpal_com_plan_id_5a1092_idx'),
        ),
        migrations.AddIndex(
            model_name='plancomment',
            index=models.Index(fields=['activity', 'created_at'], name='planpal_com_activit_a57b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment', 'reaction'], name='planpal_com_comment_bff0e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='one_reaction_per_comment_user'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['user', 'created_at'], name='planpal_com_user_id_ebb18e_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_mention'),
        ),
        migrations.AddIndex(
            model_name='planworkitem',
            index=models.Index(fields=['plan', 'item_type', 'status'], name='planpal_wor_plan_id_ac7e75_idx'),
        ),
        migrations.AddIndex(
            model_name='planworkitem',
            index=models.Index(fields=['assignee', 'status', 'due_at'], name='planpal_wor_assigne_5b3028_idx'),
        ),
    ]
