# Generated by Django 5.2.6 on 2026-09-16 05:59

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0018_plan_is_template_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payment_note', models.TextField(blank=True)),
                ('split_strategy', models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact amount')], max_length=20)),
                ('participants', models.JSONField(default=list)),
                ('payments', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planpal_recurring_expenses',
                'ordering': ['next_run_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='correction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='corrects_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='planpals.expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='entry_type',
            field=models.CharField(choices=[('original', 'Original'), ('correction', 'Correction')], db_index=True, default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='occurrence_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Invoice or receipt image/document', max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Payment receipt image/document', max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='responded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('CREATE_AVAILABILITY_POLL', 'Create Availability Poll'), ('CREATE_WORK_ITEM', 'Create Work Item'), ('UPDATE_WORK_ITEM', 'Update Work Item'), ('CREATE_COMMENT', 'Create Comment'), ('PIN_COMMENT', 'Pin Comment'), ('UNPIN_COMMENT', 'Unpin Comment'), ('CLONE_PLAN', 'Clone Plan'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_REQUESTED', 'Settlement Requested'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('SETTLEMENT_REJECTED', 'Settlement Rejected'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('GROUP_INVITE_CREATED', 'Group Invite Created'), ('GROUP_INVITE_REVOKED', 'Group Invite Revoked'), ('GROUP_JOINED_VIA_INVITE', 'Group Joined Via Invite'), ('GROUP_INVITE_FAILED', 'Group Invite Failed'), ('GROUP_JOIN_REQUESTED', 'Group Join Requested'), ('GROUP_JOIN_REQUEST_APPROVED', 'Group Join Request Approved'), ('GROUP_JOIN_REQUEST_REJECTED', 'Group Join Request Rejected'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_REMINDER', 'Plan Reminder'), ('GROUP_JOIN', 'Group Join'), ('GROUP_INVITE', 'Group Invite'), ('ROLE_CHANGED', 'Role Changed'), ('PLAN_UPDATED', 'Plan Updated'), ('NEW_MESSAGE', 'New Message'), ('BUDGET_ALERT', 'Budget Alert'), ('LARGE_EXPENSE', 'Large Expense'), ('EXPENSE_ADDED', 'Expense Added'), ('SETTLEMENT_REQUESTED', 'Settlement Requested'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('SETTLEMENT_REJECTED', 'Settlement Rejected'), ('SETTLEMENT_REMINDER', 'Settlement Reminder')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['to_user', 'status'], name='settlement_to_status_idx'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='planpals.plan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='planpals.recurringexpense'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['plan', 'entry_type'], name='expense_plan_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['recurrence', 'occurrence_at'], name='expense_recur_occ_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('recurrence', 'occurrence_at'), name='unique_recurring_expense_occurrence'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['is_active', 'next_run_at'], name='recurring_due_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexpense',
            index=models.Index(fields=['plan', 'is_active'], name='recurring_plan_active_idx'),
        ),
    ]
