# Generated by Django 5.2.6 on 2026-09-16 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0019_sprint4_finance_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('question', models.CharField(max_length=240)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_polls', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_polls', to='planpals.group')),
            ],
            options={
                'db_table': 'planpal_group_polls',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupPollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('text', models.CharField(max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='planpals.grouppoll')),
            ],
            options={
                'db_table': 'planpal_group_poll_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planpals.grouppolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planpals.grouppoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_group_poll_votes',
            },
        ),
        migrations.CreateModel(
            name='LiveLocationShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('consent_granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_location_shares', to='planpals.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_location_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_live_location_shares',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('push_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=64)),
                ('daily_digest_enabled', models.BooleanField(db_index=True, default=False)),
                ('daily_digest_hour', models.PositiveSmallIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planpal_notification_preferences',
                'indexes': [models.Index(fields=['daily_digest_enabled', 'daily_digest_hour'], name='notif_digest_schedule_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grouppoll',
            index=models.Index(fields=['group', 'is_closed', 'created_at'], name='planpal_gro_group_i_b10f68_idx'),
        ),
        migrations.AddConstraint(
            model_name='grouppolloption',
            constraint=models.UniqueConstraint(fields=('poll', 'text'), name='unique_group_poll_option_text'),
        ),
        migrations.AddIndex(
            model_name='grouppollvote',
            index=models.Index(fields=['poll', 'user'], name='planpal_gro_poll_id_134932_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppollvote',
            index=models.Index(fields=['option', 'created_at'], name='planpal_gro_option__c1b885_idx'),
        ),
        migrations.AddConstraint(
            model_name='grouppollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='unique_group_poll_option_vote'),
        ),
        migrations.AddIndex(
            model_name='livelocationshare',
            index=models.Index(fields=['conversation', 'is_active', 'expires_at'], name='live_location_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='livelocationshare',
            index=models.Index(fields=['user', 'is_active'], name='live_location_user_idx'),
        ),
    ]
