# Generated by Django 5.2.6 on 2026-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0020_sprint5_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppoll',
            name='client_mutation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livelocationshare',
            name='client_mutation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
