# Generated by Django 5.2.6 on 2026-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0021_sprint5_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('CREATE_PLAN', 'Create Plan'), ('UPDATE_PLAN', 'Update Plan'), ('DELETE_PLAN', 'Delete Plan'), ('COMPLETE_PLAN', 'Complete Plan'), ('CREATE_ACTIVITY', 'Create Activity'), ('UPDATE_ACTIVITY', 'Update Activity'), ('CREATE_AVAILABILITY_POLL', 'Create Availability Poll'), ('CREATE_GROUP_POLL', 'Create Group Poll'), ('CLOSE_GROUP_POLL', 'Close Group Poll'), ('START_LIVE_LOCATION', 'Start Live Location'), ('STOP_LIVE_LOCATION', 'Stop Live Location'), ('CREATE_WORK_ITEM', 'Create Work Item'), ('UPDATE_WORK_ITEM', 'Update Work Item'), ('CREATE_COMMENT', 'Create Comment'), ('PIN_COMMENT', 'Pin Comment'), ('UNPIN_COMMENT', 'Unpin Comment'), ('CLONE_PLAN', 'Clone Plan'), ('UPDATE_BUDGET', 'Update Budget'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('SETTLEMENT_REQUESTED', 'Settlement Requested'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('SETTLEMENT_REJECTED', 'Settlement Rejected'), ('JOIN_GROUP', 'Join Group'), ('LEAVE_GROUP', 'Leave Group'), ('ADD_MEMBER', 'Add Member'), ('REMOVE_MEMBER', 'Remove Member'), ('CHANGE_ROLE', 'Change Role'), ('GROUP_INVITE_CREATED', 'Group Invite Created'), ('GROUP_INVITE_REVOKED', 'Group Invite Revoked'), ('GROUP_JOINED_VIA_INVITE', 'Group Joined Via Invite'), ('GROUP_INVITE_FAILED', 'Group Invite Failed'), ('GROUP_JOIN_REQUESTED', 'Group Join Requested'), ('GROUP_JOIN_REQUEST_APPROVED', 'Group Join Request Approved'), ('GROUP_JOIN_REQUEST_REJECTED', 'Group Join Request Rejected'), ('DELETE_GROUP', 'Delete Group'), ('NOTIFICATION_OPENED', 'Notification Opened')], db_index=True, help_text='Normalized audit action name', max_length=50),
        ),
    ]
