# Generated by Django 5.2.6 on 2026-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0022_sprint5_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
