# Generated by Django 5.2.6 on 2026-10-08 02:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0025_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('destination', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=500)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='planpals.plan')),
            ],
            options={
                'db_table': 'planpal_plan_publications',
            },
        ),
        migrations.CreateModel(
            name='FriendTripInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('pending_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_invitations', to='planpals.friendship')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_trip_invitation', to='planpals.group')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trip_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trip_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planpal_friend_trip_invitations',
                'indexes': [models.Index(fields=['recipient', 'status', 'created_at'], name='planpal_fri_recipie_9f1957_idx')],
            },
        ),
    ]
