# Generated by Django 5.2.6 on 2026-10-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0027_sync_group_plan_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtripinvitation',
            name='friendship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_invitations', to='planpals.friendship'),
        ),
    ]
