# Generated by Django 5.2.6 on 2026-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpals', '0028_alter_friendtripinvitation_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_REMINDER', 'Plan Reminder'), ('GROUP_JOIN', 'Group Join'), ('GROUP_INVITE', 'Group Invite'), ('FRIEND_TRIP_INVITE', 'Friend Trip Invite'), ('ROLE_CHANGED', 'Role Changed'), ('PLAN_UPDATED', 'Plan Updated'), ('NEW_MESSAGE', 'New Message'), ('BUDGET_ALERT', 'Budget Alert'), ('LARGE_EXPENSE', 'Large Expense'), ('EXPENSE_ADDED', 'Expense Added'), ('SETTLEMENT_REQUESTED', 'Settlement Requested'), ('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('SETTLEMENT_REJECTED', 'Settlement Rejected'), ('SETTLEMENT_REMINDER', 'Settlement Reminder')], db_index=True, max_length=50),
        ),
    ]
