// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GIETwZj5CNGQtZR2CPqDCkCYLZ6SZrc',
    appId: '1:539351209558:web:0bc0dce41f915f15f88df7',
    messagingSenderId: '539351209558',
    projectId: 'alapp-ffa74',
    authDomain: 'alapp-ffa74.firebaseapp.com',
    storageBucket: 'alapp-ffa74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GIETwZj5CNGQtZR2CPqDCkCYLZ6SZrc',
    appId: '1:539351209558:android:0bc0dce41f915f15f88df7',
    messagingSenderId: '539351209558',
    projectId: 'alapp-ffa74',
    storageBucket: 'alapp-ffa74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GIETwZj5CNGQtZR2CPqDCkCYLZ6SZrc',
    appId: '1:539351209558:ios:0bc0dce41f915f15f88df7',
    messagingSenderId: '539351209558',
    projectId: 'alapp-ffa74',
    storageBucket: 'alapp-ffa74.firebasestorage.app',
    iosBundleId: 'com.example.planpalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1GIETwZj5CNGQtZR2CPqDCkCYLZ6SZrc',
    appId: '1:539351209558:macos:0bc0dce41f915f15f88df7',
    messagingSenderId: '539351209558',
    projectId: 'alapp-ffa74',
    storageBucket: 'alapp-ffa74.firebasestorage.app',
    iosBundleId: 'com.example.planpalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1GIETwZj5CNGQtZR2CPqDCkCYLZ6SZrc',
    appId: '1:539351209558:windows:0bc0dce41f915f15f88df7',
    messagingSenderId: '539351209558',
    projectId: 'alapp-ffa74',
    authDomain: 'alapp-ffa74.firebaseapp.com',
    storageBucket: 'alapp-ffa74.firebasestorage.app',
  );
}
